/**
 * Ignore patterns used by the Obsidian community plugin review scanner.
 * Source: Obsidian team (2026-06). May change over time in eslint-plugin-obsidianmd.
 */
export const obsidianScannerIgnores = [
  "node_modules",
  "dist",
  "build",
  "pkg",
  "test-vault",
  ".obsidian",
  "**/.obsidian/**",
  "esbuild.config.mjs",
  "version-bump.mjs",
  "**/*.test.*",
  "**/*.tests.*",
  "**/*.spec.*",
  "**/*.specs.*",
  "**/test/**",
  "**/tests/**",
  "**/__tests__/**",
  "**/mocks/**",
  "**/__mocks__/**",
  "**/*.cjs",
  "**/*.mjs",
  "**/*.cts",
  "**/*.mts",
  "**/vite*",
  "**/scripts/**",
  "**/docs/**",
  "**/i18n/**",
  "**/i18next/**",
  "**/locale/**",
  "**/locales/**",
  "**/translations/**",
  "**/l10n/**",
  ".pnpm-store",
  "**/testUtils**",
  "automation/**",
  "e2e-tests/**",
];

/** Built release artifacts and repo tooling not meant for ESLint. */
export const repoReleaseIgnores = [
  "release-artifacts",
  "main.js",
  "styles.css",
  "main.css",
  "data.json",
  "checksums.txt",
  "versions.json",
  "test-release.js",
  "**/release.js",
  "**/postcss.config.js",
  "**/tailwind.config.js",
  "**/jest.config.*",
  "**/.next/**",
  "**/.expo/**",
  "**/.turbo/**",
  "**/coverage/**",
];
