import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import builtins from "builtin-modules";
import postcss from 'esbuild-postcss';
import { normalizeCssHexInDirectory } from "./normalize-css-hex.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const isGithubAction = process.env.GITHUB_ACTIONS === "true";

// Determine output directory based on environment
const outdir = isGithubAction ? "dist" : "../..";

const cssPostProcessPlugin = {
	name: "css-post-process",
	setup(build) {
		build.onEnd(() => postProcessCss(outdir));
	},
};

function postProcessCss(outputDir) {
	const resolvedDir = path.resolve(outputDir);
	normalizeCssHexInDirectory(resolvedDir);
	const stylesPath = path.join(resolvedDir, "styles.css");
	const mainPath = path.join(resolvedDir, "main.css");
	if (fs.existsSync(stylesPath)) {
		fs.copyFileSync(stylesPath, mainPath);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "index.ts",
		styles: "styles.css",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"sharp",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	platform: "node",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outdir,
	plugins: [
		postcss({
			plugins: {
				tailwindcss: {},
				autoprefixer: {},
			},
			inject: false,
			extract: true,
		}),
		cssPostProcessPlugin,
	],
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		'process.env.GITHUB_ACTIONS': JSON.stringify(process.env.GITHUB_ACTIONS || "false"),
	},
	loader: {
		'.ts': 'ts',
		'.wasm': 'binary',
	},
	tsconfig: "tsconfig.json",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
